name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build, unit tests and integration tests
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          grype db update
      - name: Code vulnerability scanning
        run: |
          grype dir:${{ github.workspace }} -o sarif > results.sarif --fail-on high || true
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v4
        if: success() || failure()
        with:
          sarif_file: results.sarif
          wait-for-processing: true